import 'package:bloc/bloc.dart';
import 'package:meta/meta.dart';
import 'package:worldcup/constant/app_assets.dart';
import 'package:worldcup/entities/mdl_score.dart';

part 'home_page_state.dart';

class HomePageCubit extends Cubit<HomePageState> {
  HomePageCubit() : super(HomePageInitial());

  final List<MDLScore> ausScore = [
    MDLScore(
      four: 0,
      playerName: 'David Warner',
      six: 6,
      strikeRate: 78.85,
      totalBall: 52,
      totalRun: 41,
      playerOutInfo: 'c & b Kuldeep Yadav',
      image: AssetImages.davidWarner,
    ),
    MDLScore(
      four: 0,
      playerName: 'Mitchell Marsh',
      six: 0,
      totalBall: 6,
      totalRun: 0,
      playerOutInfo: 'c Virat Kohli b Jasprit Bumrah',
      image: AssetImages.mitchellMarsh,
    ),
    MDLScore(
      four: 0,
      playerName: 'Steave Smith',
      six: 5,
      strikeRate: 64.79,
      totalBall: 71,
      totalRun: 46,
      playerOutInfo: 'b Ravindra Jadeja',
      image: AssetImages.stevenSmith,
    ),
    MDLScore(
        four: 0,
        playerName: 'Marnus Labuschagne',
        six: 1,
        strikeRate: 65.85,
        totalBall: 41,
        totalRun: 27,
        playerOutInfo: 'c KL Rahul b Ravindra Jadeja',
        image: AssetImages.marnusLabuschagne),
    MDLScore(
      four: 0,
      playerName: 'Glenn Maxwell',
      six: 1,
      strikeRate: 60.00,
      totalBall: 24,
      totalRun: 15,
      playerOutInfo: 'b Kuldeep Yadav',
      image: AssetImages.glennMaxwell,
    ),
    MDLScore(
      four: 0,
      playerName: 'Alex Carey',
      six: 0,
      strikeRate: 0.00,
      totalBall: 2,
      totalRun: 0,
      playerOutInfo: 'lbw b Ravindra Jadeja',
      image: AssetImages.alexCarey,
    ),
    MDLScore(
        four: 0,
        playerName: 'Travis Head',
        six: 0,
        strikeRate: 40.00,
        totalBall: 20,
        totalRun: 8,
        playerOutInfo: 'c Hardik Pandya b R. Ashwin',
        image: AssetImages.travisHead),
  ];

  final List<MDLScore> indScore = [
    MDLScore(
      four: 4,
      playerName: 'Rohit Sharma',
      six: 3,
      strikeRate: 151.61,
      totalBall: 31,
      totalRun: 47,
      playerOutInfo: 'c Travis Head b Glenn Maxwell',
      image: AssetImages.rohitSharma,
    ),
    MDLScore(
      four: 0,
      playerName: 'Shubman Gill',
      six: 0,
      totalBall: 7,
      totalRun: 4,
      strikeRate: 57.14,
      playerOutInfo: 'c Adam Zampa b Mitchell Starc',
      image: AssetImages.shubmanGill,
    ),
    MDLScore(
      four: 4,
      playerName: 'Virat Kohli',
      six: 0,
      strikeRate: 85.71,
      totalBall: 63,
      totalRun: 54,
      playerOutInfo: 'b Pat Cummins',
      image: AssetImages.viratKohli,
    ),
    MDLScore(
        four: 1,
        playerName: 'Shreyas Iyer',
        six: 0,
        strikeRate: 133.33,
        totalBall: 3,
        totalRun: 4,
        playerOutInfo: 'c Josh Lnglis b Pat Cummins',
        image: AssetImages.shreyasIyer),
    MDLScore(
      four: 1,
      playerName: 'KL Rahul',
      six: 0,
      strikeRate: 61.68,
      totalBall: 107,
      totalRun: 66,
      playerOutInfo: 'c Josh Lnglis b Josh Hazlewood',
      image: AssetImages.klRahul,
    ),
    MDLScore(
      four: 0,
      playerName: 'Ravindra Jadeja',
      six: 0,
      strikeRate: 40.91,
      totalBall: 22,
      totalRun: 9,
      playerOutInfo: 'c Josh Lnglis b Josh Hazlewood',
      image: AssetImages.ravindraJadeja,
    ),
    MDLScore(
      four: 1,
      playerName: 'SuryaKumar Yadav',
      six: 0,
      strikeRate: 64.29,
      totalBall: 28,
      totalRun: 18,
      playerOutInfo: 'c Josh Lnglis b Josh Hazlewood',
      image: AssetImages.suryakumarYadav,
    ),
    MDLScore(
      four: 1,
      playerName: 'Mohammed Shami',
      six: 0,
      strikeRate: 60.00,
      totalBall: 10,
      totalRun: 6,
      playerOutInfo: 'c Josh Lnglis b Mitchell Starc',
      image: AssetImages.mohammedShami,
    ),
    MDLScore(
      four: 0,
      playerName: 'Jasprit Bumrah',
      six: 0,
      strikeRate: 33.33,
      totalBall: 3,
      totalRun: 1,
      playerOutInfo: 'lbw b Adam Zampa',
      image: AssetImages.jaspritBumrah,
    ),
    MDLScore(
      four: 0,
      playerName: 'Kuldeep Yadav',
      six: 0,
      strikeRate: 55.56,
      totalBall: 18,
      totalRun: 10,
      playerOutInfo: 'run out(Mamus Labuschagne)',
      image: AssetImages.kuldeepYadav,
    ),
    MDLScore(
      four: 1,
      playerName: 'Mohammed Siraj',
      six: 0,
      strikeRate: 112.50,
      totalBall: 8,
      totalRun: 9,
      playerOutInfo: 'not out',
      image: AssetImages.mohammedSiraj,
    ),
  ];

  List<String> icons = [
    AssetImages.icHome,
    AssetImages.icTv,
    AssetImages.icCalendar,
    AssetImages.icDocument,
    AssetImages.icSetting,
  ];
}
